# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a63cbc8e3e0855c0092e0197c8d50a2545732717304f848d907b6ba09c197b0cd0cdd1394a32189c54214cde9c824c6e1bd9902bb1176312d7ba90cb3445489

test:
  secret_key_base: 94a3db978bdcedb2b6ce85f985dbe99b3e8b4b5de724a3795aafa24a4b3966e2cafb457fa2ae748329afc778c5309dff110d5ee39511a06cafe7ffc5ffb19745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
